# ─── Identification du projet ─────────────────────────────────────────────────
sonar.projectKey=rfc-connect
sonar.projectName=RFC Connect

# ─── Sources ──────────────────────────────────────────────────────────────────
sonar.sources=backend

# ─── Tests ────────────────────────────────────────────────────────────────────
sonar.tests=backend
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# ─── Exclusions ───────────────────────────────────────────────────────────────
sonar.exclusions=\
  **/node_modules/**, \
  **/coverage/**, \
  **/*.test.js, \
  **/*.spec.js, \
  **/dist/**, \
  **/build/**, \
  frontend/**

# ─── Rapports de coverage ─────────────────────────────────────────────────────
sonar.javascript.lcov.reportPaths=\
  backend/auth-service/coverage/lcov.info,\
  backend/user-service/coverage/lcov.info,\
  backend/task-service/coverage/lcov.info,\
  backend/project-service/coverage/lcov.info,\
  backend/conge-service/coverage/lcov.info,\
  backend/notification-service/coverage/lcov.info

# ───  résoudre les chemins relatifs des lcov ───────
sonar.javascript.lcov.reportPaths.basedir=backend

# ─── Encoding ─────────────────────────────────────────────────────────────────
sonar.sourceEncoding=UTF-8