apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas.gateway }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      serviceAccountName: rfc-waiter
      {{- include "rfc.dns.config" . | nindent 6 }}
      {{- include "rfc.init.mongodb" . | nindent 6 }}
      containers:
        - name: api-gateway
          image: {{ .Values.image.registry }}/rfc-api-gateway:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            {{- include "rfc.env.common" . | nindent 12 }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api-gateway
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "102.141.206.201"