image:
  registry: nourchouket2000
  tag: latest
  pullPolicy: Always

replicas:
  auth:         1
  user:         1
  task:         1
  project:      1
  conge:        1
  notification: 1
  gateway:      1
  frontend:     1
  mongodb:      1

resources:
  requests:
    cpu:    "100m"
    memory: "128Mi"
  limits:
    cpu:    "500m"
    memory: "512Mi"

probes:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
mongodb:
  storage: "5Gi"
mongo:
  uriAuth:    "mongodb://mongodb.dev.svc.cluster.local:27017/auth"
  uriUser:    "mongodb://mongodb.dev.svc.cluster.local:27017/user"
  uriTask:    "mongodb://mongodb.dev.svc.cluster.local:27017/task"
  uriProject: "mongodb://mongodb.dev.svc.cluster.local:27017/project"
  uriConge:   "mongodb://mongodb.dev.svc.cluster.local:27017/conge"
  uriNotif:   "mongodb://mongodb.dev.svc.cluster.local:27017/notif"

secrets:
  jwtSecret: ""

services:
  authUrl:    "http://auth-service.dev.svc.cluster.local:5001"
  userUrl:    "http://user-service.dev.svc.cluster.local:5002"
  taskUrl:    "http://task-service.dev.svc.cluster.local:5003"
  projectUrl: "http://project-service.dev.svc.cluster.local:5004"
  congeUrl:   "http://conge-service.dev.svc.cluster.local:5005"
  notifUrl:   "http://notification-service.dev.svc.cluster.local:5006"
  apiUrl:     "http://102.141.206.201:5000"  
