[jenkins]
10.0.2.4 ansible_user=nouradmin ansible_ssh_private_key_file=~/.ssh/k8s-nour ansible_python_interpreter=/usr/bin/python3

[jenkins:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
jenkins_home=/var/lib/jenkins
kubectl_version=v1.30.1